// src/gui/root/components/toolbar-item/toolbar-item.tsx
import { h } from "preact";
import './toolbar-item.scss'

type ToolbarItemProps = {
    icon?: string,
    text?: string,
    onClick?: () => void
}

export const ToolbarItem = (
    { icon, text, onClick }: ToolbarItemProps = {}
) => <div 
    className="component-toolbar-item"
    onClick={onClick}>
    <i className={`fal fa-${icon}`}></i>
    <p>{text}</p>
</div>

// src/app/components/toolbar-item/toolbar-item.component.ts
import { Input, Component } from '@angular/core';

@Component({
  selector: 'app-toolbar-item',
  templateUrl: './toolbar-item.component.html',
  styleUrls: ['./toolbar-item.component.scss']
})
export class ToolbarItemComponent {
  @Input() icon = ''
  @Input() text = ''
}

<i [class]="'fas fa-' + icon"></i>
<p [innerHtml]="text"></p>
